### ISSUE TITLE
Bad Gateway

### ISSUE THREAD

**Issue by sahithyandev** [yungookim/spelling.io#2]
I run this command in my windows 10 command prompt.
`cURL` http://api.spelling.io/api/query/en/atmos`

But it returned me this

"<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.8.0</center>
</body>
</html>"

![image](https://user-images.githubusercontent.com/29434759/63093845-4a9e7e00-bf84-11e9-964b-0b2453926b7a.png)

Why it happens?

**Comment by yungookim** [comment]
@KSahithyan server was down :P fixed.

**Comment by sahithyandev** [comment]
Thank God. I think I should use your service instead of using Yandex's.
But Do your service support other languages (like Tamil, my mother tongue)?

**Comment by yungookim** [comment]
Only English is supported. This was done 6 years ago as a side project, but you can extend it to other languages if you have a corpus. You can create a PostDB instance, dump the words into https://github.com/yungookim/spelling.io/blob/master/schema/table.sql then run it locally. The process is pretty light.

**Comment by sahithyandev** [comment]
I will try that out, If I can.
